export const EQUATION_CATEGORIES = [
  {
    name: 'Math',
    items: [
      { name: 'Fraction', value: '\\frac{a}{b}', render: '\\frac{a}{b}' },
      { name: 'Square Root', value: '\\sqrt{x}', render: '\\sqrt{x}' },
      { name: 'N-th Root', value: '\\sqrt[n]{x}', render: '\\sqrt[n]{x}' },
      { name: 'Power/Superscript', value: 'x^2', render: 'x^2' },
      { name: 'Subscript', value: 'x_i', render: 'x_i' },
      { name: 'Absolute Value', value: '|x|', render: '|x|' },
      { name: 'Plus-Minus', value: '\\pm', render: '\\pm' },
      { name: 'Minus-Plus', value: '\\mp', render: '\\mp' },
      { name: 'Multiply (Cross)', value: '\\times', render: '\\times' },
      { name: 'Multiply (Dot)', value: '\\cdot', render: '\\cdot' },
      { name: 'Divide', value: '\\div', render: '\\div' },
      { name: 'Factorial', value: 'n!', render: 'n!' },
      { name: 'Degree', value: '^{\\circ}', render: '^{\\circ}' },
      { name: 'Percent', value: '\\%', render: '\\%' },
      { name: 'Function', value: 'f(x)', render: 'f(x)' },
      { name: 'Logarithm', value: '\\log(x)', render: '\\log' },
      { name: 'Natural Log', value: '\\ln(x)', render: '\\ln' },
      { name: 'Exponential', value: 'e^x', render: 'e^x' },
      { name: 'In', value: '\\in', render: '\\in' },
      { name: 'Not In', value: '\\notin', render: '\\notin' },
      { name: 'Subset', value: '\\subset', render: '\\subset' },
      { name: 'Subset/Eq', value: '\\subseteq', render: '\\subseteq' },
      { name: 'Superset', value: '\\supset', render: '\\supset' },
      { name: 'Superset/Eq', value: '\\supseteq', render: '\\supseteq' },
      { name: 'Union', value: '\\cup', render: '\\cup' },
      { name: 'Intersection', value: '\\cap', render: '\\cap' },
      { name: 'Empty Set', value: '\\emptyset', render: '\\emptyset' },
      { name: 'Set Difference', value: '\\setminus', render: '\\setminus' },
      { name: 'Natural Numbers', value: '\\mathbb{N}', render: '\\mathbb{N}' },
      { name: 'Integers', value: '\\mathbb{Z}', render: '\\mathbb{Z}' },
      { name: 'Rational Numbers', value: '\\mathbb{Q}', render: '\\mathbb{Q}' },
      { name: 'Real Numbers', value: '\\mathbb{R}', render: '\\mathbb{R}' },
      { name: 'Complex Numbers', value: '\\mathbb{C}', render: '\\mathbb{C}' },
      { name: 'For All', value: '\\forall', render: '\\forall' },
      { name: 'Exists', value: '\\exists', render: '\\exists' },
      { name: 'Not Exists', value: '\\nexists', render: '\\nexists' },
      { name: 'Logical And', value: '\\land', render: '\\land' },
      { name: 'Logical Or', value: '\\lor', render: '\\lor' },
      { name: 'Logical Not', value: '\\neg', render: '\\neg' },
      { name: 'Therefore', value: '\\therefore', render: '\\therefore' },
      { name: 'Because', value: '\\because', render: '\\because' },
      { name: 'Equal', value: '=', render: '=' },
      { name: 'Not Equal', value: '\\neq', render: '\\neq' },
      { name: 'Equivalent', value: '\\equiv', render: '\\equiv' },
      { name: 'Approx', value: '\\approx', render: '\\approx' },
      { name: 'Similar', value: '\\sim', render: '\\sim' },
      { name: 'Congruent', value: '\\cong', render: '\\cong' },
      { name: 'Proportional', value: '\\propto', render: '\\propto' },
      { name: 'Less Than', value: '<', render: '<' },
      { name: 'Greater Than', value: '>', render: '>' },
      { name: 'Less/Eq', value: '\\leq', render: '\\leq' },
      { name: 'Greater/Eq', value: '\\geq', render: '\\geq' },
      { name: 'Much Less', value: '\\ll', render: '\\ll' },
      { name: 'Much Greater', value: '\\gg', render: '\\gg' },
      { name: 'Perpendicular', value: '\\perp', render: '\\perp' },
      { name: 'Parallel', value: '\\parallel', render: '\\parallel' },
    ],
  },
  {
    name: 'Calculus',
    items: [
      { name: 'Derivative', value: '\\frac{d}{dx}', render: '\\frac{d}{dx}' },
      {
        name: 'Partial',
        value: '\\frac{\\partial}{\\partial x}',
        render: '\\partial',
      },
      { name: 'Integral', value: '\\int_{a}^{b} x \\,dx', render: '\\int' },
      {
        name: 'Double Integral',
        value: '\\iint_{D} dx \\,dy',
        render: '\\iint',
      },
      {
        name: 'Triple Integral',
        value: '\\iiint_{V} dx \\,dy \\,dz',
        render: '\\iiint',
      },
      {
        name: 'Line Integral',
        value: '\\oint_{C} \\vec{F} \\cdot d\\vec{r}',
        render: '\\oint',
      },
      { name: 'Summation', value: '\\sum_{i=1}^n i', render: '\\sum' },
      { name: 'Product', value: '\\prod_{i=1}^n i', render: '\\prod' },
      { name: 'Limit', value: '\\lim_{x \\to \\infty} f(x)', render: '\\lim' },
      { name: 'Infinity', value: '\\infty', render: '\\infty' },
      { name: 'Nabla/Del', value: '\\nabla', render: '\\nabla' },
      { name: 'Laplacian', value: '\\nabla^2', render: '\\nabla^2' },
      { name: 'First Derivative (Dot)', value: '\\dot{x}', render: '\\dot{x}' },
      { name: 'Second Derivative', value: '\\ddot{x}', render: '\\ddot{x}' },
      { name: 'Third Derivative', value: '\\dddot{x}', render: '\\dddot{x}' },
      { name: 'Sine', value: '\\sin(x)', render: '\\sin' },
      { name: 'Cosine', value: '\\cos(x)', render: '\\cos' },
      { name: 'Tangent', value: '\\tan(x)', render: '\\tan' },
      { name: 'Secant', value: '\\sec(x)', render: '\\sec' },
      { name: 'Cosecant', value: '\\csc(x)', render: '\\csc' },
      { name: 'Cotangent', value: '\\cot(x)', render: '\\cot' },
      { name: 'Arcsine', value: '\\arcsin(x)', render: '\\arcsin' },
      { name: 'Arccosine', value: '\\arccos(x)', render: '\\arccos' },
      { name: 'Arctangent', value: '\\arctan(x)', render: '\\arctan' },
      { name: 'Hyperbolic Sine', value: '\\sinh(x)', render: '\\sinh' },
      { name: 'Hyperbolic Cosine', value: '\\cosh(x)', render: '\\cosh' },
      { name: 'Hyperbolic Tangent', value: '\\tanh(x)', render: '\\tanh' },
    ],
  },
  {
    name: 'Physics',
    items: [
      { name: 'Vector (Arrow)', value: '\\vec{v}', render: '\\vec{v}' },
      { name: 'Unit Vector', value: '\\hat{n}', render: '\\hat{n}' },
      { name: 'Bra', value: '\\langle \\psi |', render: '\\langle \\psi |' },
      { name: 'Ket', value: '| \\psi \\rangle', render: '| \\psi \\rangle' },
      {
        name: 'Bra-Ket',
        value: '\\langle \\phi | \\psi \\rangle',
        render: '\\langle \\phi | \\psi \\rangle',
      },
      { name: 'Reduced Planck Constant', value: '\\hbar', render: '\\hbar' },
      { name: 'Speed of Light', value: 'c', render: 'c' },
      { name: 'Gravitational Constant', value: 'G', render: 'G' },
      {
        name: 'Permittivity',
        value: '\\varepsilon_0',
        render: '\\varepsilon_0',
      },
      { name: 'Permeability', value: '\\mu_0', render: '\\mu_0' },
      { name: 'Angstrom', value: '\\mathring{A}', render: '\\mathring{A}' },
      { name: 'Ohm', value: '\\Omega', render: '\\Omega' },
    ],
  },
  {
    name: 'Matrices',
    items: [
      {
        name: 'Parenthesis Matrix',
        value: '\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}',
        render: '\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}',
      },
      {
        name: 'Bracket Matrix',
        value: '\\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix}',
        render: '\\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix}',
      },
      {
        name: 'Determinant',
        value: '\\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix}',
        render: '\\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix}',
      },
      {
        name: 'Norm/Double',
        value: '\\begin{Vmatrix} a & b \\\\ c & d \\end{Vmatrix}',
        render: '\\begin{Vmatrix} a & b \\\\ c & d \\end{Vmatrix}',
      },
      {
        name: 'Cases/Piecewise',
        value: '\\begin{cases} a & x < 0 \\\\ b & x \\geq 0 \\end{cases}',
        render: '\\begin{cases} a \\\\ b \\end{cases}',
      },
      { name: 'Right Arrow', value: '\\rightarrow', render: '\\rightarrow' },
      { name: 'Left Arrow', value: '\\leftarrow', render: '\\leftarrow' },
      { name: 'Up Arrow', value: '\\uparrow', render: '\\uparrow' },
      { name: 'Down Arrow', value: '\\downarrow', render: '\\downarrow' },
      {
        name: 'Left-Right',
        value: '\\leftrightarrow',
        render: '\\leftrightarrow',
      },
      { name: 'Implies', value: '\\implies', render: '\\implies' },
      { name: 'If and Only If', value: '\\iff', render: '\\iff' },
      { name: 'Maps To', value: '\\mapsto', render: '\\mapsto' },
      { name: 'Up-Down', value: '\\updownarrow', render: '\\updownarrow' },
      {
        name: 'Right Harpoon',
        value: '\\rightharpoonup',
        render: '\\rightharpoonup',
      },
      {
        name: 'Left Harpoon',
        value: '\\leftharpoonup',
        render: '\\leftharpoonup',
      },
    ],
  },
  {
    name: 'Greek',
    items: [
      { name: 'Alpha', value: '\\alpha', render: '\\alpha' },
      { name: 'Beta', value: '\\beta', render: '\\beta' },
      { name: 'Gamma', value: '\\gamma', render: '\\gamma' },
      { name: 'Delta', value: '\\delta', render: '\\delta' },
      { name: 'Epsilon', value: '\\epsilon', render: '\\epsilon' },
      { name: 'Zeta', value: '\\zeta', render: '\\zeta' },
      { name: 'Eta', value: '\\eta', render: '\\eta' },
      { name: 'Theta', value: '\\theta', render: '\\theta' },
      { name: 'Iota', value: '\\iota', render: '\\iota' },
      { name: 'Kappa', value: '\\kappa', render: '\\kappa' },
      { name: 'Lambda', value: '\\lambda', render: '\\lambda' },
      { name: 'Mu', value: '\\mu', render: '\\mu' },
      { name: 'Nu', value: '\\nu', render: '\\nu' },
      { name: 'Xi', value: '\\xi', render: '\\xi' },
      { name: 'Omicron', value: 'o', render: 'o' },
      { name: 'Pi', value: '\\pi', render: '\\pi' },
      { name: 'Rho', value: '\\rho', render: '\\rho' },
      { name: 'Sigma', value: '\\sigma', render: '\\sigma' },
      { name: 'Tau', value: '\\tau', render: '\\tau' },
      { name: 'Upsilon', value: '\\upsilon', render: '\\upsilon' },
      { name: 'Phi', value: '\\phi', render: '\\phi' },
      { name: 'Chi', value: '\\chi', render: '\\chi' },
      { name: 'Psi', value: '\\psi', render: '\\psi' },
      { name: 'Omega', value: '\\omega', render: '\\omega' },
      { name: 'Var epsilon', value: '\\varepsilon', render: '\\varepsilon' },
      { name: 'Var theta', value: '\\vartheta', render: '\\vartheta' },
      { name: 'Var phi', value: '\\varphi', render: '\\varphi' },
      { name: 'Capital Gamma', value: '\\Gamma', render: '\\Gamma' },
      { name: 'Capital Delta', value: '\\Delta', render: '\\Delta' },
      { name: 'Capital Theta', value: '\\Theta', render: '\\Theta' },
      { name: 'Capital Lambda', value: '\\Lambda', render: '\\Lambda' },
      { name: 'Capital Xi', value: '\\Xi', render: '\\Xi' },
      { name: 'Capital Pi', value: '\\Pi', render: '\\Pi' },
      { name: 'Capital Sigma', value: '\\Sigma', render: '\\Sigma' },
      { name: 'Capital Upsilon', value: '\\Upsilon', render: '\\Upsilon' },
      { name: 'Capital Phi', value: '\\Phi', render: '\\Phi' },
      { name: 'Capital Psi', value: '\\Psi', render: '\\Psi' },
      { name: 'Capital Omega', value: '\\Omega', render: '\\Omega' },
    ],
  },
];
